name: Unit Tests & Code Quality

on:
  push:
    branches: [ '*' ]  # Run on all branches
  pull_request:  # Run on PRs to default branch (auto-detected)
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy python-dotenv pytest

      - name: Run unit tests
        run: |
          # Run tests using pytest with verbose output
          pytest tests/ -v --tb=short
        env:
          # These are dummy values for testing - the actual bot doesn't run in CI tests
          API_KEY: "dummy_key_for_testing"
          API_KEY_SECRET: "dummy_secret_for_testing"
          ACCESS_TOKEN: "dummy_token_for_testing"
          ACCESS_TOKEN_SECRET: "dummy_token_secret_for_testing"
          BEARER_TOKEN: "dummy_bearer_token_for_testing"